export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas - no guesswork involved.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top - making your learning more organized and effective.",
  },
  {
    id: "04",
    title: "Understand the \"Why\" Behind Answers",
    description:
      "Beyond just answers - unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {
    id: "05",
    title: "Save, Organize and Revisit",
    description:
      "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off.",
  },
];

export const CARD_BG = [
  { id: 1, bgColor: "linear-gradient(135deg, #e6ff83 0%, #ffcfa 100%)" },
  { id: 2, bgColor: "linear-gradient(135deg, #ef9e7 0%, #ffdfd4 100%)" },
  { id: 3, bgColor: "linear-gradient(135deg, #eaff7f 0%, #f3fbff 100%)" },
  { id: 4, bgColor: "linear-gradient(135deg, #f17e9 0%, #ff8fb3 100%)" },
  { id: 5, bgColor: "linear-gradient(135deg, #e7f6fe 0%, #f4fffd 100%)" },
  { id: 6, bgColor: "linear-gradient(135deg, #f5f3f5 0%, #fbbfb 100%)" },
  { id: 7, bgColor: "linear-gradient(135deg, #ff4fc 0%, #ff8fb 100%)" },
  { id: 8, bgColor: "linear-gradient(135deg, #e8fef3 0%, #f5fef8 100%)" },
  { id: 9, bgColor: "linear-gradient(135deg, #f0ceff 0%, #f75ff 100%)" },
  { id: 10, bgColor: "linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)" }
];